name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installer Java et Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.9'  # spécifiez la version de Java requise
          distribution: 'adopt'
      
      - name: Configurer Maven pour utiliser Nexus
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>nexus</id><username>${{ secrets.NEXUS_USER }}</username><password>${{ secrets.NEXUS_PASS }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build et tests du projet
        run: mvn clean install

      - name: Déploiement de l'artefact dans Nexus
        run: mvn deploy
